config/routes.rb
RedmineApp::Application.routes.draw do
  resources :projects do
  	resources :proteus
  end
  # match "/proteus/:project_id", controller: "proteus", :action => "index", :via => :get #, :collection => { :create => :post }
  # map.resources :proteus
  # map.connect 'projects/:project_id/changes/:action', :controller => 'proteus'
  #get '/projects/:project_id/proteus', to: 'proteus#index'
  #get '/projects/:project_id/proteus/new', to: 'proteus#new'
  #post '/projects/:project_id/proteus/create', to: 'proteus#create'
  #get '/projects/:project_id/proteus/:id', to: 'proteus#show'
  #get '/projects/:project_id/proteus/:id/edit', to: 'proteus#edit'
  #put '/projects/:project_id/proteus/:id', to: 'proteus#update'
  #delete '/projects/:project_id/proteus/:id', to: 'proteus#destroy'
end

app/models/proteus.rb
class Proteus < ActiveRecord::Base
  unloadable

  belongs_to :proteus_status
  belongs_to :proteus_priority
  belongs_to :change_owner, :class_name => 'User', :foreign_key => 'change_owner_id'
  belongs_to :decision_owner, :class_name => 'User', :foreign_key => 'decision_owner_id'
  belongs_to :project

  has_and_belongs_to_many :resources, :class_name => 'User', :join_table => 'proteus_resources'
  has_and_belongs_to_many :reviewers, :class_name => 'User', :join_table => 'proteus_reviewers'

  validates_presence_of :proteus_status, :change_owner, :proteus_priority, :summary, :detail,
                        :services_affected, :servers_affected, :risks, :backout_strategy,
                        :reversion_procedure, :predicted_start_date, :predicted_start_time,
                        :predicted_finish_date, :predicted_finish_time

  before_save :set_submission_date, :set_accepted_date, :set_rejected_date, :set_success_date, :set_failure_date

  def allowed_statuses
    if proteus_status.nil?
      self.proteus_status_id = 1
    end

    statuses = proteus_status.find_allowed_statuses
    statuses << proteus_status unless statuses.empty?
  end

  def self.sortable_columns
    {"owner" => ["users.lastname", "users.firstname", "users.id"],
      "id" => "proteus.id",
      "project" => "projects.name",
      "submission_date" => "submission_date",
      "proteus_statuses.description" => "proteus_statuses.description",
      "proteus_priorities.description" => "proteus_priorities.description",
      "summary" => "summary",
      "predicted_start_date" => "predicted_start_date",
      "predicted_finish_date" => "predicted_finish_date",
      "actual_start_date" => "actual_start_date",
      "actual_finish_date" => "actual_finish_date"}
  end

  protected
  def set_submission_date
    if submission_date.nil?
      if self.changed? && self.proteus_status_id != 1
        self.submission_date = Date.today
      end
    end
  end

  def set_accepted_date
    if accepted_date.nil?
      if self.changed? && (self.proteus_status_id_change == [2, 3] || self.proteus_status_id_change == [4, 3])
        self.accepted_date = Date.today
      end
    end
  end

  def set_rejected_date
    if rejected_date.nil?
      if self.changed? && self.proteus_status_id_change == [2, 4]
        self.rejected_date = Date.today
      end
    end
  end

  def set_success_date
    if success_date.nil?
      if self.changed? && self.proteus_status_id_change == [3, 5]
        self.success_date = Date.today
      end
    end
  end

  def set_failure_date
    if failure_date.nil?
      if self.changed? && self.proteus_status_id_change == [3, 6]
        self.failure_date = Date.today
      end
    end
  end
end

app/controllers/proteus_controller.rb
class ProteusController < ApplicationController
  unloadable

  before_filter :find_project, :only => [:new, :create]
  before_filter :find_optional_project, :only => [:index]
  before_filter :find_change, :only => [:show, :edit, :update, :destroy]
  before_filter :build_new_change, :only => [:new, :create]
  before_filter :authorize, :except => [:index]

  helper :proteus
  include ProteusHelper
  helper :sort
  include SortHelper

  def index
    sort_init 'id', 'desc'
    sort_update (Proteus.sortable_columns)

    case params[:format]
      when 'csv', 'pdf'
        @limit = Setting.issues_export_limit.to_i
      when 'atom'
        @limit = Setting.feeds_limit.to_i
      when 'xml', 'json'
        @offset, @limit = api_offset_and_limit
      else
        @limit = per_page_option
    end

    @total = Proteus.count
    @proteus_pages = Paginator.new @total, @limit, params['page']
    @offset ||= @proteus_pages.offset
    @proteus = Proteus.all.includes(:change_owner, :proteus_status, :proteus_priority, :project).order(sort_clause).offset(@offset).limit(@limit)

    respond_to do |format|
      format.html
      format.json { render :json => @proteus }
      format.atom { render_feed(@proteus, :title => "Change Control Feed") }
      format.csv  { send_data(proteus_to_csv(@proteus), :type => 'text/csv; header=present', :filename => 'changes.csv') }
      format.pdf  { send_data(issues_to_pdf(@proteus), :type => 'application/pdf', :filename => 'export.pdf') }
    end
  end

  def new
    respond_to do |format|
      format.html
      format.json { render :json => @proteus }
    end
  end

  def create
    @proteus = Proteus.new(proteus_params)
    @proteus.project_id = @project.id

    respond_to do |format|
      if @proteus.save
        format.html { redirect_to(:action => 'show', :id => @proteus, :notice => 'Change Request was successfully created.') }
        format.json { render :json => @proteus, :status => :created, :location => @proteus }
      else
        format.html { render :action => "new" }
        format.json { render :json => @proteus.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @proteus }
    end
  end

  def edit
    update_change
  end

  def update
    update_change
    params[:proteus][:resource_ids] ||= []
    params[:proteus][:reviewer_ids] ||= []

    respond_to do |format|
      if @proteus.update_attributes(proteus_params)
        format.html { redirect_to(:action => 'show', :id => @proteus, :notice => 'Change Request was successfully updated.') }
        format.json { render :json => {}, :status => ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @proteus.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @proteus.destroy

    respond_to do |format|
      format.html { redirect_back_or_default(:action => 'index', :project_id => @project) }
      format.json { render :json => {}, :status => :ok }
    end
  end

private

  def find_change
    @proteus = Proteus.find(params[:id])
    @project = @proteus.project
    @allowed_statuses = @proteus.allowed_statuses
    @priority = ProteusPriority.all
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def update_change
    @status = ProteusStatus.all
    @user = User.all
    @allowed_statuses = @proteus.allowed_statuses
    @priority = ProteusPriority.all
  end

  def build_new_change
    if params[:id].blank?
      @proteus = Proteus.new
      @proteus.project = @project
    else
      @proteus = Proteus.new(proteus_params)
    end

    @proteus.project = @project
    update_change
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def proteus_params
    params.require(:proteus).permit(:id, :submission_date, :proteus_status_id, :change_owner_id, :proteus_priority_id, :summary, :detail, :ticket_references, :services_affected, :servers_affected, :risks, :backout_strategy, :reversion_procedure, :predicted_start_date, :predicted_start_time, :predicted_finish_date, :predicted_finish_time, :decision_owner_id, :review_notes, :actual_start_date, :actual_start_time, :actual_finish_date, :actual_finish_time, :completion_notes, :created_on, :updated_on, :project_id, :accepted_date, :rejected_date, :success_date, :failure_date, resource_ids:[], reviewer_ids:[])
  end
end

app/helpers/proteus_helper.rb
module ProteusHelper
  unloadable
  include ApplicationHelper

  def proteus_to_csv(proteus)

    Redmine::Export::CSV.generate do |csv|
      # csv header fields
      headers = [ "#",
                  "Submission Date",
                  "Project",
                  "Status",
                  "Owner",
                  "Priority",
                  "Summary",
                  "Predicted Start",
                  "Predicted Finish"
                  ]
      csv << headers.collect {|c| c.to_s}
      # csv lines
      proteus.each do |proteu|
        fields = [proteu.id,
                  format_date(proteu.submission_date),
                  proteu.project.name,
                  proteu.proteus_status.description,
                  proteu.change_owner.name,
                  proteu.proteus_priority.description,
                  proteu.summary,
                  proteu.predicted_start_date,
                  proteu.predicted_finish_date
                  ]
        csv << fields.collect {|c| c.to_s}
      end
    end
  end

  def active_status(status)
    if status == "Successful" || status == "Failed"
      return false
    else
      return true
    end
  end
end

app/views/proteus/_edit.html.erb
<%= labelled_form_for :proteus, @proteus,
                             :url => {:action => 'update', :id => @proteus},
                             :html => {:id => 'proteus-form',
                                       :class => 'tabular proteus-form',
                                       :method => :put,
                                       :multipart => true} do |f| %>

    <%= render :partial => 'form', :locals => {:f => f} %>

  <%= submit_tag "Save Changes" %>
  <%= link_to 'Back', project_proteus_path %>
<% end %>

app/views/proteus/_form.html.erb
<% if @proteus.errors.any? %>
<div id="errorExplanation">
  <h3><%= pluralize(@proteus.errors.count, "error") %> prohibited this post from being saved:</h3>
  <ul>
    <% @proteus.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<% if @proteus.new_record? || @proteus.proteus_status.description == "Draft" || @proteus.proteus_status.description == "Rejected" %>
	<div id="proteus_submission_fields">
      <p><%= f.select :proteus_status_id, @allowed_statuses.collect{|s| [s.description, s.id]}.sort, :required => true %></p>
  		<p><%= f.select :change_owner_id, @proteus.project.assignable_users.collect {|u| [u.name, u.id]}, :include_blank => true, :required => true %></p>
  		<p><%= f.select :proteus_priority_id, @priority.collect {|p| [p.description, p.id]}, :include_blank => true, :required => true %></p>
  		<p><%= f.text_field :summary, :size => 80, :required => true, :maxlength => 255 %></p>
  		<p><%= f.text_area :detail,
        	               :cols => 60,
                               :rows => (@proteus.detail.blank? ? 10 : [[10, @proteus.detail.length / 50].max, 100].min),
              		       :accesskey => accesskey(:edit),
                               :class => 'wiki-edit',
                               :required => true %></p>
                <p><%= f.text_field :ticket_references, :size => 80, :maxlength => 255 %></p>
  		<p><%= f.text_field :services_affected, :size => 80, :required => true, :maxlength => 255 %></p>
                <p><%= f.text_field :servers_affected, :size => 80, :required => true, :maxlength => 255 %></p>
  		<p><%= f.text_area :risks,
        	               :cols => 60,
              		       :rows => (@proteus.risks.blank? ? 10 : [[10, @proteus.risks.length / 50].max, 100].min),
        	               :accesskey => accesskey(:edit),
              		       :class => 'wiki-edit',
                               :required => true %></p>
  		<p><%= f.text_area :backout_strategy,
        	               :cols => 60,
              		       :rows => (@proteus.backout_strategy.blank? ? 10 : [[10, @proteus.backout_strategy.length / 50].max, 100].min),
        	               :accesskey => accesskey(:edit),
              		       :class => 'wiki-edit',
                               :required => true %></p>
  		<p><%= f.text_area :reversion_procedure,
        	               :cols => 60,
              		       :rows => (@proteus.reversion_procedure.blank? ? 10 : [[10, @proteus.reversion_procedure.length / 50].max, 100].min),
              		       :accesskey => accesskey(:edit),
              		       :class => 'wiki-edit',
              		       :required => true %></p>
  		<p><%= f.text_field :predicted_start_date, :size => 10, :required => true, :maxlength => 10 %><%= calendar_for('proteus_predicted_start_date')%> <%= f.time_select :predicted_start_time, {:minute_step => 15} %> </p>
  		<p><%= f.text_field :predicted_finish_date, :size => 10, :required => true, :maxlength => 10 %><%= calendar_for('proteus_predicted_finish_date')%> <%= f.time_select :predicted_finish_time, {:minute_step => 15} %> </p>
  		<p id="resources_form"><label>Who do you need?</label>
    		<% @proteus.project.users.sort.each do |user| %>
      			<label class="floating"><%= check_box_tag 'proteus[resource_ids][]', user.id, @proteus.resources.include?(user) %> <%=h user %></label>
    		<% end %>
   		</p>
	</div>

  <div id="hidden_resources" style="display:none;">
    <p id="reviewers_form"><label>Review Team</label>
    <% @proteus.project.users.sort.each do |user| %>
      <label class="floating"><%= check_box_tag 'proteus[reviewer_ids][]', user.id, @proteus.reviewers.include?(user) %> <%=h user %></label>
    <% end %>
    </p>
  </div>
<% end %>

<% if @proteus.proteus_status.description == "Submitted" %>

  <div id="proteus_review_fields">
    <p><%= f.select :proteus_status_id, @allowed_statuses.collect{|s| [s.description, s.id]}.sort, :required => true %></p>
    <p><%= f.select :decision_owner_id, @proteus.project.assignable_users.collect {|d| [d.name, d.id]}, :include_blank => true, :required => true %></p>
    <p id="reviewers_form"><label>Review Team</label>
    <% @proteus.project.users.sort.each do |user| %>
      <label class="floating"><%= check_box_tag 'proteus[reviewer_ids][]', user.id, @proteus.reviewers.include?(user) %> <%=h user %></label>
    <% end %></p>
    <p><%= f.text_area :review_notes,
        	               :cols => 60,
              		       :rows => (@proteus.review_notes.blank? ? 10 : [[10, @proteus.review_notes.length / 50].max, 100].min),
              		       :accesskey => accesskey(:edit),
              		       :class => 'wiki-edit' %></p>
  </div>

  <div id="hidden_resources" style="display:none;">
    <p id="resources_form"><label>Who do you need?</label>
    <% @proteus.project.users.sort.each do |user| %>
      <label class="floating"><%= check_box_tag 'proteus[resource_ids][]', user.id, @proteus.resources.include?(user) %> <%=h user %></label>
    <% end %>
    </p>
  </div>

<% end %>

<% if @proteus.proteus_status.description == "Accepted" %>

  <div id="proteus_completion_fields">
    <p><%= f.select :proteus_status_id, @allowed_statuses.collect{|s| [s.description, s.id]}.sort, :required => true %></p>
    <p><%= f.text_field :actual_start_date, :size => 10, :required => true, :maxlength => 10 %><%= calendar_for('proteus_actual_start_date')%> <%= f.time_select :actual_start_time, {:minute_step => 5} %> </p>
    <p><%= f.text_field :actual_finish_date, :size => 10, :required => true, :maxlength => 10 %><%= calendar_for('proteus_actual_finish_date')%> <%= f.time_select :actual_finish_time, {:minute_step => 5} %> </p>
    <p><%= f.text_area :completion_notes,
        	               :cols => 60,
              		       :rows => (@proteus.completion_notes.blank? ? 10 : [[10, @proteus.completion_notes.length / 50].max, 100].min),
              		       :accesskey => accesskey(:edit),
              		       :class => 'wiki-edit' %></p>
  </div>

  <div id="hidden_resources" style="display:none;">
    <p id="resources_form"><label>Who do you need?</label>
    <% @proteus.project.users.sort.each do |user| %>
      <label class="floating"><%= check_box_tag 'proteus[resource_ids][]', user.id, @proteus.resources.include?(user) %> <%=h user %></label>
    <% end %>
    </p>
    <p id="reviewers_form"><label>Review Team</label>
    <% @proteus.project.users.sort.each do |user| %>
      <label class="floating"><%= check_box_tag 'proteus[reviewer_ids][]', user.id, @proteus.reviewers.include?(user) %> <%=h user %></label>
    <% end %>
    </p>
  </div>

<% end %>

<%= wikitoolbar_for 'proteus_detail' %>
<%= wikitoolbar_for 'proteus_risks' %>
<%= wikitoolbar_for 'proteus_backout_strategy' %>
<%= wikitoolbar_for 'proteus_reversion_procedure' %>
<%= wikitoolbar_for 'proteus_review_notes' %>
<%= wikitoolbar_for 'proteus_completion_notes' %>

app/views/proteus/edit.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'proteus', :plugin => 'redmine_proteus' %>
<% end %>

<h2>Edit Change Request</h2>

<% labelled_tabular_form_for :proteus, @proteus,
                             :url => {:action => 'update', :id => @proteus},
                             :html => {:id => 'proteus-form',
                                       :class => 'tabular proteus-form',
                                       :method => :put,
                                       :multipart => true} do |f| %>

    <%= render :partial => 'proteus/form', :locals => {:f => f} %>
  
  <%= submit_tag "Save Changes" %>
  <%= link_to 'Back', proteus_path %>
<% end %>

app/views/proteus/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'proteus', :plugin => 'redmine_proteus' %>
<% end %>

<div class="contextual">
  <%= link_to 'New Change Request', new_project_proteu_path(:project_id => @project), :class => 'icon icon-add' %>
</div>

<h2>Change Requests</h2>

<% if @total == 0 %>
  <p>No items found...</p>
<% else %>
<div class="autoscroll">
  <table class="list requests">
    <thead>
      <tr>
        <%= sort_header_tag('id', :caption => '#', :default_order => 'desc') %>
        <%= sort_header_tag('project', :caption => 'Project') %>
        <%= sort_header_tag('summary', :caption => 'Summary') %>
        <%= sort_header_tag('submission_date', :caption => 'Submission Date') %>
        <%= sort_header_tag('proteus_statuses.description', :caption => 'Status') %>
        <%= sort_header_tag('owner', :caption => 'Owner') %>
        <%= sort_header_tag('proteus_priorities.description', :caption => 'Priority') %>
        <%= sort_header_tag('predicted_start_date', :caption => 'Expected Start') %>
        <%= sort_header_tag('predicted_finish_date', :caption => 'Expected Finish') %>
        <%= sort_header_tag('actual_start_date', :caption => 'Actual Start') %>
        <%= sort_header_tag('actual_finish_date', :caption => 'Actual Finish') %>
      </tr>
    </thead>

    <% @proteus.each do |proteus| %>
    <tr id="proteus-<%= proteus.id %>" class="proteus">
      <td class="id"><%= link_to proteus.id, :controller => 'proteus', :action => 'show', :id => proteus %></td>
      <td class="project"><%= link_to proteus.project.name, :controller => 'projects', :action => 'show', :id => proteus.project_id %></td>
      <td class="summary"><%= link_to proteus.summary, :controller => 'proteus', :action => 'show', :id => proteus %></td>
      <td class="submission_date"><%= format_date(proteus.submission_date) %></td>
      <td class="status"><%= proteus.proteus_status.description %></td>
      <td class="owner"><%= link_to proteus.change_owner.name, :controller => 'users', :action => 'show', :id => proteus.change_owner %></td>
      <td class="priority"><%= proteus.proteus_priority.description %></td>
      <td class="predicted_start_date"><%= format_date(proteus.predicted_start_date) %></td>
      <td class="predicted_finish_date"><%= format_date(proteus.predicted_finish_date) %></td>
      <td class="actual_start_date"><%= format_date(proteus.actual_start_date) %></td>
      <td class="actual_finish_date"><%= format_date(proteus.actual_finish_date) %></td>
    </tr>
    <% end %>
  </table>
</div>
<span class="pagination"><%= pagination_links_full @proteus_pages, @total %></span>
<% end %>

<% other_formats_links do |f| %>
  <%#= f.link_to 'Atom', :url => params.merge(:key => User.current.rss_key) %>
  <%= f.link_to 'CSV', :url => params %>
  <%#= f.link_to 'PDF', :url => params %>
<% end %>

app/views/proteus/new.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'proteus', :plugin => 'redmine_proteus' %>
<% end %>

<h2>New Change Request</h2>

<%= labelled_form_for :proteus, @proteus,
                             :url => {:action => 'create', :project_id => @project},
                             :html => {:multipart => true,
                                       :id => 'proteus-form',
                                       :class => 'tabular new-proteus-form'} do |f| %>
  <div class="box">
    <%= render :partial => 'proteus/form', :locals => {:f => f} %>
  </div>
  <%= submit_tag "Create" %>
  <%= link_to 'Back', project_proteus_path %>
<% end %>

app/views/proteus/show.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'proteus', :plugin => 'redmine_proteus' %>
<% end %>

<% if active_status(@proteus.proteus_status.description) %>
  <div class="contextual">
    <%= link_to 'Update', {:controller => 'proteus', :action => 'edit', :id => @proteus }, :onclick => 'showAndScrollTo("update"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
    <%= link_to 'Delete', {:controller => 'proteus', :action => 'destroy', :id => @proteus}, :confirm => 'Are you sure you want to delete the selected change request?', :method => :delete, :class => 'icon icon-del' %>
  </div>
<% end %>

<h2>Change #<%= @proteus.id %></h2>
<div class="change_details">
  <div class="subject">
    <h3><%= @proteus.summary %></h3>
  </div>

  <div class="halign" id="proteus_request_basics">
    <table class="proteus_basics">
      <caption>Request Basics</caption>
      <tbody>
        <tr>
          <th class="change_owner">Owner:</th><td class="change_owner"><%= link_to_user(@proteus.change_owner) %></td>
        </tr>
        <tr>
          <th class="status">Status:</th><td class="status"><%= @proteus.proteus_status.description %></td>
        </tr>
        <tr>
          <th class="priority">Priority:</th><td class="priority"><%= @proteus.proteus_priority.description %></td>
        </tr>
        <tr>
          <th class="submitted_date">Submitted:</th><td class="submitted_date"><%= format_date(@proteus.submission_date) %></td>
        </tr>
        <tr>
          <th class="predicted_start">Expected Start:</th><td class="predicted_start"><%= format_date(@proteus.predicted_start_date) %> <%= format_time(@proteus.predicted_start_time, false) %></td>
        </tr>
        <tr>
          <th class="predicted_finish">Expected Finish:</th><td class="predicted_finish"><%= format_date(@proteus.predicted_finish_date) %> <%= format_time(@proteus.predicted_finish_time, false) %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="halign" id="proteus_review_basics">
    <table class="proteus_basics">
      <caption>Review Basics</caption>
      <tbody>
        <tr>
          <th class="decision_owner">Review Lead:</th><td class="decision_owner"><%= link_to_user(@proteus.decision_owner) %></td>
        </tr>
        <tr>
          <th class="accepted_date">Accepted:</th><td class="accepted_date"><%= format_date(@proteus.accepted_date) %></td>
        </tr>
        <tr>
          <th class="rejected_date">Rejected:</th><td class="rejected_date"><%= format_date(@proteus.rejected_date) %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="halign" id="proteus_change_basics">
    <table class="proteus_basics">
      <caption>Change Basics</caption>
      <tbody>
        <tr>
          <th class="success_date">Successful:</th><td class="success_date"><%= format_date(@proteus.success_date) %></td>
        </tr>
        <tr>
          <th class="failure_date">Failed:</th><td class="failure_date"><%= format_date(@proteus.failure_date) %></td>
        </tr>
        <tr>
          <th class="actual_start">Actual Start:</th><td class="actual_start"><%= format_date(@proteus.actual_start_date) %> <%= format_time(@proteus.actual_start_time, false) %></td>
        </tr>
        <tr>
          <th class="actual_finish">Actual Finish:</th><td class="actual_finish"><%= format_date(@proteus.actual_finish_date) %> <%= format_time(@proteus.actual_finish_time, false) %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <hr/>

  <p><strong>Specifics</strong></p>
  <table class="proteus_specifics">
    <tbody>
      <tr>
        <th class="servers_affected">Servers Affected:</th><td class="servers_affected"><%= @proteus.servers_affected %></td>
      </tr>
      <tr>
        <th class="services_affected">Services Affected:</th><td class="services_affected"><%= @proteus.services_affected %></td>
      </tr>
      <tr>
        <th class="ticket_references">Ticket References:</th><td class="ticket_references"><%= @proteus.ticket_references %></td>
      </tr>
      <tr>
        <th class="who">Who's Required:</th><td class="who"><%= @proteus.resources.map{|u| [u.name]}.join(", ") %></td>
      </tr>
      <tr>
        <th class="review_team">Review Team:</th><td class="review_team"><%= @proteus.reviewers.map{|u| [u.name]}.join(", ") %></td>
      </tr>
    </tbody>
  </table>

  <hr/>

  <p><strong>Detail</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :detail %>
  </div>
  <p><strong>Risks</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :risks %>
  </div>
  <p><strong>Backout Strategy</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :backout_strategy %>
  </div>
  <p><strong>Reversion Procedure</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :reversion_procedure %>
  </div>
  <p><strong>Review Notes</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :review_notes %>
  </div>
  <p><strong>Completion Notes</strong></p>
  <div class="wiki">
    <%= textilizable @proteus, :completion_notes %>
  </div>
</div>

<% if active_status(@proteus.proteus_status.description) %>
  <div class="contextual">
    <%= link_to 'Update', {:controller => 'proteus', :action => 'edit', :id => @proteus }, :onclick => 'showAndScrollTo("update"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
    <%= link_to 'Delete', {:controller => 'proteus', :action => 'destroy', :id => @proteus}, :confirm => 'Are you sure you want to delete the selected change request?', :method => :delete, :class => 'icon icon-del' %>
  </div>
<% end %>

<% if authorize_for('proteus','edit') %>
  <div id="update" style="display:none;">
  <h3>Update Change Request</h3>
  <%= render :partial => 'edit' %>
  </div>
<% end %>